BEGIN;

-- O padrão também marca todos os contratos já cadastrados como sujeitos ao SENAR.
ALTER TABLE public.contratos
  ADD COLUMN IF NOT EXISTS desconta_senar boolean NOT NULL DEFAULT true;

CREATE TABLE IF NOT EXISTS public.contrato_recebimentos (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  contrato_id bigint NOT NULL REFERENCES public.contratos(id),
  data_recebimento date NOT NULL,
  valor numeric(14, 2) NOT NULL CHECK (valor > 0),
  observacao text,
  usuario_id uuid REFERENCES public.users(id) ON DELETE SET NULL,
  criado_em timestamptz NOT NULL DEFAULT now()
);

CREATE INDEX IF NOT EXISTS contrato_recebimentos_contrato_data_idx
  ON public.contrato_recebimentos (contrato_id, data_recebimento DESC, id DESC);

-- Contratos já marcados como recebidos não tinham lançamentos individuais.
-- A linha de abertura preserva o status anterior sem inventar parcelas.
-- Seu valor já considera o desconto de SENAR de 0,2%.
INSERT INTO public.contrato_recebimentos (contrato_id, data_recebimento, valor, observacao)
SELECT c.id,
       COALESCE(c.data_recebimento, c.data_contrato),
       ROUND(c.quantidade_kg * c.preco_por_saca / 60, 2)
         - CASE WHEN c.desconta_senar
             THEN ROUND(ROUND(c.quantidade_kg * c.preco_por_saca / 60, 2) * 0.002, 2)
             ELSE 0 END,
       'Saldo inicial de contrato marcado como recebido antes do controle de recebimentos.'
FROM public.contratos c
WHERE c.contrato_recebido IS TRUE
  AND ROUND(c.quantidade_kg * c.preco_por_saca / 60, 2)
        - CASE WHEN c.desconta_senar
            THEN ROUND(ROUND(c.quantidade_kg * c.preco_por_saca / 60, 2) * 0.002, 2)
            ELSE 0 END > 0
  AND NOT EXISTS (
    SELECT 1 FROM public.contrato_recebimentos r WHERE r.contrato_id = c.id
  );

COMMIT;
